// Every piece of wording (and section photo) on the public pages, with its default.
// Admin → Website text shows one form per page built from this list; a saved value
// replaces the default, and clearing a field brings the default back.
// Text can include {placeholders} that the page fills with live figures, e.g. {minDeposit}.
// Shared by server and client: no server-only imports.

export type CopySubField = { name: string; label: string; type: 'text' | 'textarea' }
export type CopyField =
  | { name: string; label: string; type: 'text' | 'textarea' | 'image'; default: string; help?: string }
  | { name: string; label: string; type: 'list'; itemLabel: string; fields: CopySubField[]; default: Record<string, string>[]; help?: string }

export type CopyPage = { key: string; title: string; description: string; paths: string[]; fields: CopyField[] }

const text = (name: string, label: string, value: string, help?: string): CopyField => ({ name, label, type: value.length > 90 ? 'textarea' : 'text', default: value, help })
const image = (name: string, label: string, value: string): CopyField => ({ name, label, type: 'image', default: value, help: 'Wide photo, at least 1600 pixels across.' })
const steps = (name: string, label: string, value: { title: string; text: string }[]): CopyField => ({
  name,
  label,
  type: 'list',
  itemLabel: 'item',
  fields: [
    { name: 'title', label: 'Title', type: 'text' },
    { name: 'text', label: 'Text', type: 'textarea' },
  ],
  default: value,
})
const lines = (name: string, label: string, value: string[]): CopyField => ({
  name,
  label,
  type: 'list',
  itemLabel: 'line',
  fields: [{ name: 'text', label: 'Text', type: 'textarea' }],
  default: value.map((t) => ({ text: t })),
})
const faqs = (name: string, label: string, value: { q: string; a: string }[]): CopyField => ({
  name,
  label,
  type: 'list',
  itemLabel: 'question',
  fields: [
    { name: 'q', label: 'Question', type: 'text' },
    { name: 'a', label: 'Answer', type: 'textarea' },
  ],
  default: value,
})

export const COPY_PAGES: CopyPage[] = [
  {
    key: 'site',
    title: 'Header, footer and chat button',
    description: 'Wording that appears on every page.',
    paths: ['/'],
    fields: [
      text('footer.blurb', 'Footer: about Akristal', 'The Akristal Group Limited builds homes in Africa, lists homes across Africa, the Gulf and beyond, and finishes them with Akristal interiors and furniture.'),
      text('whatsapp.message', 'WhatsApp button: first message', 'Hello Akristal, I would like some help.'),
      text('whatsapp.label', 'WhatsApp button: name read by screen readers', 'Chat with Akristal on WhatsApp'),
    ],
  },
  {
    key: 'home',
    title: 'Home page text',
    description: 'Headings, introductions and photos of every section on the home page. The hero headline, ticker and figures are in Home page settings.',
    paths: ['/'],
    fields: [
      text('developments.title', 'Developments: heading', 'Akristal Developments'),
      text('developments.intro', 'Developments: introduction', 'Homes and neighbourhoods we plan, build and sell. Purchase properties from the off-plan stage to the finished home via Akristal.'),
      text('developments.action', 'Developments: link', 'All developments'),
      text('featured.title', 'Featured homes: heading', 'Homes listed with Akristal Brokers & Agents'),
      text('featured.intro', 'Featured homes: introduction', 'Houses, apartments and land for sale and rent. The Akristal team checks every listing before it goes live.'),
      text('featured.action', 'Featured homes: link', 'See all homes'),
      text('markets.title', 'Where we work: heading', 'Where we work'),
      text('markets.intro', 'Where we work: introduction', 'The head office is located in Kigali, Rwanda. Akristal Brokers & Agents also list homes across the Africa region, the Gulf and the globe.'),
      text('marquee.title', 'Moving homes strip: heading', 'On the market now'),
      text('marquee.intro', 'Moving homes strip: introduction', 'A moving look at homes for sale and rent today. Hover or tap to pause.'),
      text('marquee.action', 'Moving homes strip: link', 'Browse all homes'),
      text('interiors.title', 'Interior design panel: heading', 'Interior design'),
      text('interiors.text', 'Interior design panel: text', 'We design and decorate homes, offices and short-let apartments, from the first plan to the finished room.'),
      text('interiors.cta', 'Interior design panel: link', 'See Akristal interiors'),
      image('interiors.image', 'Interior design panel: photo', '/images/interiors/living-warm.webp'),
      text('furniture.title', 'Furniture panel: heading', 'Furniture'),
      text('furniture.text', 'Furniture panel: text', 'Sofas, beds, dining sets and lighting chosen to finish a home. Ask about any piece on WhatsApp.'),
      text('furniture.cta', 'Furniture panel: link', 'Browse furniture'),
      image('furniture.image', 'Furniture panel: photo', '/images/interiors/living-wood.webp'),
      text('finance.title', 'Finance: heading', 'What a home costs each month'),
      text('finance.intro', 'Finance: introduction ({price} is the example price)', 'Two ways to pay for a {price} home: a bank mortgage, or an Akristal Pay Small Small plan paid directly to Akristal, with or without your bank.'),
      text('finance.mortgageText', 'Finance: mortgage card text', 'We help you prepare a bank application and guide you from approval to handover.'),
      text('finance.mortgageCta', 'Finance: mortgage card button', 'Work out your mortgage'),
      text('finance.planText', 'Finance: Pay Small Small card text ({minDeposit}, {longest})', 'Pay Akristal directly on selected homes and developments: from {minDeposit}% deposit, over up to {longest}. A bank loan is optional.'),
      text('finance.planCta', 'Finance: Pay Small Small card button', 'See Pay Small Small plans'),
      text('finance.disclaimer', 'Finance: small print', 'Estimates for illustration only, not a loan offer. Rates, deposits and terms depend on the lender or plan and are confirmed in writing.'),
      text('people.title', 'Brokers & Agents: heading', 'Akristal Brokers & Agents'),
      text('people.intro', 'Brokers & Agents: introduction', 'Agents and broker companies who sell and let homes with Akristal. Message one directly, or call the Akristal office.'),
      text('people.action', 'Brokers & Agents: link', 'Become an agent or broker'),
      text('people.noBrokers', 'Brokers & Agents: text while no broker is published', 'Broker companies can register to sell and let homes with Akristal.'),
      text('partners.title', 'Partners: heading', 'Trusted by leading brands and partners'),
      text('partners.intro', 'Partners: introduction', 'Developers, brokers, banks and suppliers who work with Akristal across Africa and beyond.'),
      text('partners.cta', 'Partners: question before the link', 'Want to work with Akristal?'),
      text('partners.ctaLink', 'Partners: link', 'Talk to us about a partnership'),
      text('reviews.title', 'Reviews: heading', 'Loved by Akristal clients'),
      text('reviews.intro', 'Reviews: introduction', 'Words from buyers, tenants and investors who trusted Akristal with one of the biggest decisions of their lives.'),
      text('reviews.emptyTitle', 'Reviews: heading while there are none', 'Bought, rented or built with Akristal?'),
      text('reviews.emptyText', 'Reviews: text while there are none', 'Tell others how it went. Every review is read by the Akristal team before it is published here.'),
      text('insights.title', 'Insights: heading', 'Stay updated with the latest insights'),
      text('insights.intro', 'Insights: introduction', 'Guides on buying, financing and furnishing a home, from the Akristal team.'),
      text('sell.title', 'Sell: heading', 'Selling or letting a home?'),
      text('sell.intro', 'Sell: introduction', 'Tell us about it and an Akristal broker or agent will contact you with a price estimate and a plan to sell or let it.'),
      image('sell.image', 'Sell: photo', '/images/homes/villa-1.webp'),
    ],
  },
  {
    key: 'pay-small-small',
    title: 'Pay Small Small text',
    description: 'Wording on the Pay Small Small page. Deposit and term figures come from Pay Small Small plans; use {minDeposit}, {maxDeposit}, {shortest} and {longest} to show them.',
    paths: ['/pay-small-small'],
    fields: [
      text('hero.title', 'Heading', 'Pay Small Small'),
      text('hero.intro', 'Introduction', 'Own your home without needing a bank loan. Pay a deposit of {minDeposit}% to {maxDeposit}%, then the rest in monthly instalments over up to {longest}, directly to Akristal. Have a bank that can lend you part? Akristal can work with it.'),
      text('bank.label', 'Bank loan: label', 'Bank loan'),
      text('bank.value', 'Bank loan: value', 'Optional'),
      text('bank.note', 'Bank loan: note', 'Not needed, but Akristal can work with your bank if you have one.'),
      text('how.title', 'How it works: heading', 'How it works'),
      steps('how.steps', 'How it works: steps', [
        { title: 'Choose your home', text: 'Pick an eligible listing or a unit in an Akristal development.' },
        { title: 'Pay the deposit', text: 'From {minDeposit}% to {maxDeposit}% of the price when you sign your Pay Small Small agreement.' },
        { title: 'Pay monthly', text: 'Spread the balance over {shortest} to {longest}. Your bank loan can cover part of it.' },
        { title: 'Complete and move in', text: 'Your agreement sets out handover and title transfer once the plan is paid.' },
      ]),
      text('planner.title', 'Calculator: heading', 'Plan your payments'),
      text('planner.intro', 'Calculator: introduction', "Enter the price, choose your deposit and how long to pay, add your bank's part if you have one, and see every payment with its due date."),
      text('eligibility.title', 'Who can apply: heading', 'Who can apply'),
      text('terms.title', 'Terms: heading', 'The terms, in plain words'),
      lines('terms.items', 'Terms: points', [
        'You sign a Pay Small Small agreement before paying the deposit.',
        'Instalments are due monthly on the dates shown in your schedule.',
        'Your agreement explains handover, title transfer, early payment and missed payments.',
        'Prices and plan options are confirmed by Akristal for each home.',
      ]),
      text('apply.title', 'Apply: heading', 'Apply for Pay Small Small'),
      text('apply.intro', 'Apply: introduction', 'Tell us which home you want and how you would like to pay. We will confirm the plan and send your agreement.'),
      text('faq.title', 'Questions: heading', 'Questions about Pay Small Small'),
      faqs('faq.items', 'Questions', [
        { q: 'Do I need a bank loan?', a: 'No. You pay Akristal directly. If you can borrow part of the price from your bank, tell us which bank when you apply: Akristal can work with your bank so the loan covers part of the balance and Pay Small Small covers the rest.' },
        { q: 'How is Pay Small Small different from a mortgage?', a: 'A mortgage is a bank loan repaid with interest over many years, after the bank checks your income. Pay Small Small is a payment plan with Akristal itself, over {shortest} to {longest}. You can also combine the two.' },
        { q: 'Which homes can I buy with Pay Small Small?', a: 'Selected listings and units in Akristal developments. Ask your broker or agent, or look for "Pay Small Small available" on a development.' },
        { q: 'Can I pay faster than the schedule?', a: 'Tell us when you apply. Your agreement sets out how early payments work.' },
        { q: 'What if I miss a payment?', a: 'Contact us straight away. Your agreement explains what happens with late or missed payments, so read it carefully before you sign.' },
        { q: 'Is there extra cost for paying in instalments?', a: 'Any premium for longer plans is shown in the calculator above and stated in your agreement.' },
      ]),
    ],
  },
  {
    key: 'join',
    title: 'Become an agent text',
    description: 'Wording on Become an Akristal agent. Commission levels and questions are in Agent programme. Use {commission} for the commission rate.',
    paths: ['/join'],
    fields: [
      text('hero.title', 'Heading', 'Sell homes with Akristal'),
      text('hero.intro', 'Introduction', "Join an agency that also builds. Sell Akristal Developments, list your clients' homes, and earn more as your sales grow."),
      image('hero.image', 'Photo', '/images/places/kigali-hillside.webp'),
      text('why.title', 'Why join: heading', 'Why agents choose Akristal'),
      steps('why.items', 'Why join: reasons', [
        { title: 'Homes no one else can sell', text: 'Akristal Developments, from Le Centurium City to Pearl View Residence, are sold through Akristal Brokers & Agents.' },
        { title: 'Buyers who are ready to talk', text: 'Viewing requests, WhatsApp messages and enquiries from akristal.com go straight to the agent on the listing.' },
        { title: 'Ways for buyers to pay', text: 'Pay Small Small instalments and mortgage support help your buyers get from "I like it" to a signed agreement.' },
        { title: 'A profile that works for you', text: 'Your own page with your homes for sale and rent, past sales, contact buttons and verified client reviews.' },
      ]),
      text('earn.title', 'How you earn: heading', 'How you earn'),
      text('earn.intro', 'How you earn: introduction', 'Akristal charges a {commission}% commission on a sale. You keep a share of it on every sale you complete, and your share grows with your track record.'),
      text('requirements.title', 'Requirements: heading', 'What we look for'),
      lines('requirements.items', 'Requirements', [
        'You live in, and know, the area you want to sell in',
        'A valid ID, and a real estate licence where the law requires one',
        'A smartphone with WhatsApp, and time to answer clients the same day',
        'Honesty with buyers and sellers. Every review on your profile is checked',
      ]),
      text('steps.title', 'How to join: heading', 'How to join'),
      steps('steps.items', 'How to join: steps', [
        { title: 'Apply', text: 'Fill in the form below. It takes about five minutes.' },
        { title: 'Interview', text: 'Meet the Akristal sales team in Kigali, Abuja or by video call.' },
        { title: 'Onboarding', text: 'Learn the Akristal Developments, the sales process, and set up your profile page.' },
        { title: 'Your first listing', text: 'Start with an Akristal development or bring your own client.' },
      ]),
      text('faq.title', 'Questions: heading', 'Questions agents ask'),
      text('apply.title', 'Apply: heading', 'Apply to join'),
      text('apply.intro', 'Apply: introduction', "Tell us about yourself and where you sell. We'll be in touch about an interview."),
    ],
  },
  {
    key: 'join-broker',
    title: 'Register a broker text',
    description: 'Wording on Register a broker company.',
    paths: ['/join/broker'],
    fields: [
      text('hero.title', 'Heading', 'Register your broker company with Akristal'),
      text('hero.intro', 'Introduction', 'Broker companies work under The Akristal Group: your team sells and lets homes with Akristal, and your company is listed among Akristal Brokers & Agents.'),
      steps('benefits', 'What brokers get', [
        { title: 'Sell Akristal Developments', text: 'Offer your clients homes from Akristal Developments, from off-plan to finished.' },
        { title: 'A page for your company', text: 'Your logo, the areas you cover and contact buttons on the Akristal Brokers page.' },
        { title: 'Leads from akristal.com', text: 'Enquiries about your listings reach your team directly, by WhatsApp, phone or email.' },
        { title: 'Ways for buyers to pay', text: 'Pay Small Small and mortgage support help your clients get to a signed agreement.' },
      ]),
      text('steps.title', 'How registration works: heading', 'How registration works'),
      steps('steps.items', 'How registration works: steps', [
        { title: 'Register', text: 'Tell us about the company in the form below.' },
        { title: 'Meet the Akristal team', text: 'We review your registration and arrange a meeting in Kigali, Abuja or by video call.' },
        { title: 'Sign the broker agreement', text: 'It sets out commission, listing standards and how leads are shared.' },
        { title: 'Go live', text: 'Your company page goes live and you can start listing homes.' },
      ]),
      text('apply.title', 'Form: heading', 'Company details'),
      text('apply.intro', 'Form: introduction', 'It takes about five minutes. The Akristal team replies to every registration.'),
    ],
  },
  {
    key: 'about',
    title: 'About page text',
    description: 'Wording and photo on the About page. Figures come from Home page settings; offices from Phone numbers and offices.',
    paths: ['/about'],
    fields: [
      text('hero.title', 'Heading', 'We build, sell and finish homes'),
      text('hero.intro', 'Introduction', 'The Akristal Group Limited is a real estate and lifestyle company with head offices in Kigali for East Africa and Abuja for West Africa. We develop new neighbourhoods, sell and let homes across Africa, the Gulf and beyond, finance them with Pay Small Small, and furnish them.'),
      image('hero.image', 'Photo', '/images/places/kigali.webp'),
      text('what.title', 'What we do: heading', 'What we do'),
      text('what.intro', 'What we do: introduction', 'Most clients come to us for a home. Many stay for the rest: the loan, the interiors, the furniture and the move.'),
      {
        name: 'what.groups',
        label: 'What we do: services',
        type: 'list',
        itemLabel: 'group',
        fields: [
          { name: 'title', label: 'Group', type: 'text' },
          { name: 'items', label: 'Services, one per line', type: 'textarea' },
        ],
        default: [
          { title: 'Build', items: 'Real estate development\nConstruction\nArchitectural design\nInfrastructure' },
          { title: 'Sell and let', items: 'Residential property, local and international\nCommercial property, local and international\nLease and rental services\nProperty management' },
          { title: 'Finance', items: 'In-house financing, including Pay Small Small\nF.Y.L. Company (Fund Your Lifestyle)' },
          { title: 'Finish', items: 'Interior and exterior decoration\nHome automation\nFurniture' },
          { title: 'And more', items: 'Outsourcing management\nConsulting for manufacturing companies\nEvent planning\nTransport and car hire' },
        ],
      },
      text('values.title', 'Values: heading', 'What we stand for'),
      steps('values.items', 'Values', [
        { title: 'Transparency', text: 'Clear prices, clear terms and honest advice in every transaction.' },
        { title: 'Security', text: 'Your documents, payments and personal data handled with care.' },
        { title: 'Excellence', text: 'Quality in what we build, what we list and how we finish it.' },
        { title: 'Customer focus', text: 'We start from what you need, not from what we have to sell.' },
      ]),
      text('team.title', 'Management team: heading', 'The management team'),
      text('team.intro', 'Management team: introduction', 'Engineers, surveyors, lawyers and managers who lead every Akristal project.'),
      text('offices.title', 'Offices: heading', 'Offices'),
    ],
  },
  {
    key: 'directories',
    title: 'Brokers, agents and team pages',
    description: 'Headings and introductions on the Agents, Brokers, Management team, Insights, Reviews and Contact pages.',
    paths: ['/agents', '/brokers', '/management', '/insights', '/reviews', '/contact'],
    fields: [
      text('agents.title', 'Agents: heading', 'Akristal Agents'),
      text('agents.intro', 'Agents: introduction', 'Talk to someone who knows the street, the developer and the paperwork. Every Akristal agent can show you homes, arrange viewings and walk you through mortgage or Pay Small Small options.'),
      text('brokers.title', 'Brokers: heading', 'Akristal Brokers'),
      text('brokers.intro', 'Brokers: introduction', 'Broker companies registered with Akristal. Each one sells and lets homes with the Akristal team, including Akristal Developments.'),
      text('brokers.cta', 'Brokers: banner heading', 'Run a brokerage?'),
      text('brokers.ctaText', 'Brokers: banner text', "Register your company with Akristal to sell Akristal Developments and list your clients' homes here."),
      text('management.title', 'Management team: heading', 'Management team'),
      text('management.intro', 'Management team: introduction', 'The people who lead The Akristal Group Limited: planning, building, selling and finishing every Akristal home.'),
      text('insights.title', 'Insights: heading', 'Insights'),
      text('insights.intro', 'Insights: introduction', 'Plain guides to buying, financing and furnishing a home, written by the Akristal team.'),
      text('reviews.title', 'Reviews: heading', 'Client reviews'),
      text('reviews.intro', 'Reviews: introduction', 'Words from people who bought, rented or built with Akristal.'),
      text('reviews.formTitle', 'Reviews: form heading', 'Share your experience'),
      text('reviews.formIntro', 'Reviews: form introduction', 'Your review helps other buyers and tenants. The Akristal team reads every review before it is published.'),
      text('contact.title', 'Contact: heading', 'Contact us'),
      text('contact.intro', 'Contact: introduction', 'The quickest way to reach Akristal is WhatsApp. You can also call, email, or send the form below.'),
    ],
  },
  {
    key: 'projects',
    title: 'Developments page text',
    description: 'Heading and introduction on the Developments page.',
    paths: ['/projects'],
    fields: [
      text('hero.title', 'Heading', 'Akristal Developments'),
      text('hero.intro', 'Introduction', 'Neighbourhoods we plan, build and sell, from new satellite cities in Rwanda’s Eastern Province to finished homes in Abuja. Purchase properties from the off-plan stage to the finished home via Akristal.'),
      text('empty.title', 'No developments at a stage: heading', 'No developments at this stage right now'),
      text('empty.text', 'No developments at a stage: text', 'See every Akristal development instead.'),
    ],
  },
  {
    key: 'mortgage',
    title: 'Mortgage page text',
    description: 'Wording and photo on the Mortgage page. Partner banks are in Lenders.',
    paths: ['/mortgage'],
    fields: [
      text('hero.title', 'Heading', 'Buy with a mortgage'),
      text('hero.intro', 'Introduction', 'Know your monthly payment before you fall in love with a home, then let Akristal help you through the bank.'),
      image('hero.image', 'Photo', '/images/homes/villa-2.webp'),
      text('how.title', 'How it works: heading', 'How it works'),
      steps('how.steps', 'How it works: steps', [
        { title: 'Check what you can afford', text: 'Use the calculators below to set a realistic budget before you start viewing.' },
        { title: 'Get pre-qualified', text: 'Send a few details. Akristal reviews your figures and tells you which lenders fit.' },
        { title: 'Choose your home', text: 'Pick a listing or an Akristal development. Your Akristal broker or agent negotiates the price.' },
        { title: 'Approval and handover', text: 'The bank values the home and approves the loan. You sign, pay the deposit and collect the keys.' },
      ]),
      text('calculator.title', 'Calculator: heading', 'Mortgage calculator'),
      text('calculator.intro', 'Calculator: introduction', 'Change the price, deposit, rate and term to see your monthly payment and the full repayment schedule.'),
      text('afford.title', 'Affordability: heading', 'How much can you afford?'),
      text('afford.intro', 'Affordability: introduction', 'A quick guide based on your income, existing repayments and savings.'),
      text('prequalify.title', 'Pre-qualify: heading', 'Get pre-qualified'),
      text('prequalify.intro', 'Pre-qualify: introduction', 'Tell us about your income and deposit. Akristal will tell you which lenders fit and what to prepare. It does not affect your credit record.'),
      text('lenders.title', 'Lenders: heading', 'Akristal lending partners'),
      text('lenders.empty', 'Lenders: text while none are published', 'Partner lenders will be listed here. Until then, send the form and Akristal will point you to lenders that fit your situation.'),
      text('pss.title', 'Pay Small Small banner: heading', 'Prefer to skip the bank?'),
      text('pss.text', 'Pay Small Small banner: text ({longest})', 'With Pay Small Small you pay Akristal directly: a deposit, then monthly instalments over up to {longest}.'),
      text('faq.title', 'Questions: heading', 'Mortgage questions'),
      faqs('faq.items', 'Questions', [
        { q: 'How much deposit do I need?', a: 'Banks usually ask for 10% to 30% of the price, depending on the country, the lender and your income. The calculator starts with a typical figure for each currency.' },
        { q: 'Can I get a mortgage if I live abroad?', a: 'Some lenders offer diaspora mortgages. Say where you live and earn in the pre-qualification form and Akristal will point you to the options.' },
        { q: 'What documents will the bank ask for?', a: 'Usually ID, proof of income (payslips or business statements), bank statements for the last six to twelve months, and the sale agreement for the home.' },
        { q: 'Mortgage or Pay Small Small?', a: 'A mortgage spreads the cost over many years through a bank. Pay Small Small spreads it over {shortest} to {longest}, paid directly to Akristal, and your bank can cover part of it. The right choice depends on your budget and how fast you want to own the home outright.' },
      ]),
    ],
  },
  {
    key: 'interior-design',
    title: 'Interior design page text',
    description: 'Wording and photo on the Interior design page. Portfolio projects are in Interior portfolio.',
    paths: ['/interior-design'],
    fields: [
      text('hero.title', 'Heading', 'Interiors, finished by the people who built them'),
      text('hero.intro', 'Introduction', 'Design, fit-out and furnishing for homes, short-let apartments and offices, from first sketch to the last cushion.'),
      image('hero.image', 'Photo', '/images/interiors/living-warm.webp'),
      text('services.title', 'Services: heading', 'What we do'),
      steps('services.items', 'Services', [
        { title: 'Home interiors', text: 'Layouts, finishes, lighting and furniture for a new or existing home, room by room or the whole house.' },
        { title: 'Short-let and rental styling', text: 'Durable, photogenic interiors for apartments you let, ready for guests and listing photos.' },
        { title: 'Offices and shops', text: 'Workspaces and retail interiors that suit your brand and the way your team works.' },
        { title: 'Turnkey furnishing', text: 'We supply and install everything, from sofas and beds to curtains and kitchenware, so you move straight in.' },
        { title: 'Exterior and decoration', text: 'Facades, gardens, outdoor lighting and decorative finishes, designed with the interior.' },
        { title: 'Design consultation', text: 'A session with a designer to plan colours, materials and a layout you can carry out yourself.' },
      ]),
      text('portfolio.title', 'Portfolio: heading', 'Portfolio'),
      text('portfolio.intro', 'Portfolio: introduction', 'A selection of homes and spaces Akristal has designed and furnished.'),
      text('portfolio.empty', 'Portfolio: text while empty', 'New projects are being added. Book a consultation to see more Akristal work.'),
      text('beforeAfter.title', 'Before and after: heading', 'Before and after'),
      text('process.title', 'Process: heading', 'How a project runs'),
      steps('process.items', 'Process steps', [
        { title: 'Brief', text: 'We visit or video-call, measure the space and agree what you need and your budget.' },
        { title: 'Concept', text: 'Mood boards, layouts and a colour and material palette for you to react to.' },
        { title: 'Design and quote', text: 'Detailed drawings, a furniture and finishes list, and a fixed quote.' },
        { title: 'Build and install', text: 'The Akristal team manages the work, the suppliers and the schedule on site.' },
        { title: 'Handover', text: 'A final walk-through, styling, and a snag list closed before you move in.' },
      ]),
      text('consult.title', 'Consultation: heading', 'Book a consultation'),
      text('consult.intro', 'Consultation: introduction', 'Tell us about the space. A designer will contact you to arrange a visit or video call.'),
    ],
  },
  {
    key: 'furniture',
    title: 'Furniture page text',
    description: 'Wording on the Furniture page. The pieces themselves are in Furniture.',
    paths: ['/furniture'],
    fields: [
      text('hero.title', 'Heading', 'Furniture'),
      text('hero.intro', 'Introduction', 'Pieces chosen to finish a home. Tap any item for sizes and colours, then order on WhatsApp with the details already filled in.'),
      text('hero.cta', 'WhatsApp button', 'Ask about something else'),
      text('empty', 'Text while the catalogue is empty', 'The catalogue is being updated. Message Akristal on WhatsApp for current pieces.'),
      text('banner.title', 'Banner: heading', 'Furnishing a whole home?'),
      text('banner.text', 'Banner: text', 'Akristal interior designers can plan and supply everything, room by room, to one budget.'),
      text('banner.cta', 'Banner: button', 'Talk to a designer'),
    ],
  },
  {
    key: 'sell',
    title: 'Sell page text',
    description: 'Wording and photo on Sell or value your home.',
    paths: ['/sell'],
    fields: [
      text('hero.title', 'Heading', 'Sell or let your home with Akristal'),
      text('hero.intro', 'Introduction', 'Start with a free valuation. Akristal will tell you what your home is likely to fetch, and how it would be marketed.'),
      image('hero.image', 'Photo', '/images/homes/villa-3.webp'),
      text('form.title', 'Form: heading', 'Request a valuation'),
      text('form.note', 'Form: note', 'No cost and no obligation.'),
      text('why.title', 'Why list: heading', 'Why owners list with Akristal'),
      steps('why.items', 'Why list: reasons', [
        { title: 'Buyers at home and abroad', text: 'Your home is listed on akristal.com with photos, a map and monthly cost estimates that buyers in Africa and the diaspora use to decide.' },
        { title: 'A broker or agent who knows your area', text: 'One person handles viewings, questions and offers, and keeps you updated on WhatsApp.' },
        { title: 'More ways for buyers to pay', text: 'Eligible homes can be offered with Pay Small Small instalments, which widens the pool of buyers.' },
      ]),
      text('steps.title', 'Steps: heading', 'From valuation to sale'),
      steps('steps.items', 'Steps', [
        { title: 'Tell us about the home', text: 'Send the form. It takes two minutes.' },
        { title: 'Visit and price', text: 'An Akristal broker or agent visits, checks comparable homes nearby and recommends a price.' },
        { title: 'Photos and listing', text: 'Akristal prepares the listing and publishes it once you approve it.' },
        { title: 'Viewings to completion', text: 'Your broker or agent runs viewings, negotiates offers and guides the paperwork.' },
      ]),
    ],
  },
]

export const copyPage = (key: string) => COPY_PAGES.find((p) => p.key === key) ?? null

/** Fills {placeholders} with live values; unknown ones are left as typed. */
export function fill(template: string, vars: Record<string, string | number> = {}) {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m))
}
