// Generated photo registry. Every image is from Unsplash (free licence, https://unsplash.com/license).
// They are PLACEHOLDERS: replace with Akristal's own photography (same keys) before launch.

export type SiteImage = { src: string; width: number; height: number; alt: string; credit: { author: string; source: string } }

export const images = {
  heroKigaliAerial: { src: "/images/hero/kigali-aerial.webp", width: 2400, height: 1798, alt: "Aerial view of a green park and wetlands in Kigali with the city on the hills behind", credit: { author: "Protais Benjamin MUGENZI", source: "https://unsplash.com/photos/nyandungu-eco-park-aerial-view-in-kigali-d_3BZ9wISCc" } },
  placesKigali: { src: "/images/places/kigali.webp", width: 1600, height: 900, alt: "Kigali skyline at sunset", credit: { author: "Jean Claude Akarikumutima", source: "https://unsplash.com/photos/the-sun-is-setting-over-a-city-with-tall-buildings-b-HnOOPRfTI" } },
  placesKigaliHillside: { src: "/images/places/kigali-hillside.webp", width: 1600, height: 1067, alt: "Houses with clay-tile roofs on a Kigali hillside", credit: { author: "Protais Benjamin MUGENZI", source: "https://unsplash.com/photos/a-view-of-a-city-with-a-lot-of-houses-K15V22xU1zs" } },
  placesRwandaHills: { src: "/images/places/rwanda-hills.webp", width: 1600, height: 1067, alt: "Terraced hills and a lake in rural Rwanda", credit: { author: "Random Institute", source: "https://unsplash.com/photos/aerial-photography-of-hills-and-trees-KQ5djKAN35s" } },
  placesAbuja: { src: "/images/places/abuja.webp", width: 1600, height: 2133, alt: "Office towers in Abuja", credit: { author: "Praise Godwin", source: "https://unsplash.com/photos/modern-building-complex-with-a-clear-blue-sky--n9_5JHoLyg" } },
  placesLagos: { src: "/images/places/lagos.webp", width: 1600, height: 900, alt: "Lagos waterfront and skyline", credit: { author: "Nupo Deyon Daniel", source: "https://unsplash.com/photos/aerial-view-of-city-buildings-during-daytime-67ruAEYmp4c" } },
  placesDubai: { src: "/images/places/dubai.webp", width: 1600, height: 1200, alt: "Dubai skyline", credit: { author: "Riyas Mohammed", source: "https://unsplash.com/photos/a-view-of-a-city-with-a-lot-of-tall-buildings-CK9BTsQ-I1Y" } },
  homesVilla1: { src: "/images/homes/villa-1.webp", width: 1600, height: 1067, alt: "Modern two-storey villa with palm trees", credit: { author: "Tim Schmidbauer", source: "https://unsplash.com/photos/a-modern-luxurious-house-sits-among-palm-trees-_tEBCVrEnyo" } },
  homesVilla2: { src: "/images/homes/villa-2.webp", width: 1600, height: 900, alt: "White modern house with balconies", credit: { author: "WILLIAN REIS", source: "https://unsplash.com/photos/a-two-story-house-with-a-lot-of-windows-and-balconies-JwSo36TmqFA" } },
  homesVilla3: { src: "/images/homes/villa-3.webp", width: 1600, height: 827, alt: "Contemporary house with stone walls and glass", credit: { author: "VJ Von Art", source: "https://unsplash.com/photos/brown-wooden-chairs-on-white-concrete-floor-fCUJxm3V6B4" } },
  homesApartments: { src: "/images/homes/apartments.webp", width: 1600, height: 2000, alt: "Modern white apartment building with balconies", credit: { author: "Pierre Châtel-Innocenti", source: "https://unsplash.com/photos/white-concrete-building-during-daytime-gxyeia7Syuk" } },
  projectsConstructionFrame: { src: "/images/projects/construction-frame.webp", width: 1600, height: 2000, alt: "Concrete frame of an apartment building under construction", credit: { author: "Tomas", source: "https://unsplash.com/photos/a-building-under-construction-with-a-crane-in-the-background-R32rcn653D0" } },
  projectsConstructionCrane: { src: "/images/projects/construction-crane.webp", width: 1600, height: 2000, alt: "Crane above a building under construction", credit: { author: "Tomas", source: "https://unsplash.com/photos/a-crane-is-on-top-of-a-building-under-construction--qB4CrGphxk" } },
  interiorsLivingWarm: { src: "/images/interiors/living-warm.webp", width: 2000, height: 2500, alt: "Warm living room with rust-coloured sofas and ring pendant lights", credit: { author: "Ali Moradi", source: "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-lots-of-windows-2YqoWuYoFgI" } },
  interiorsLivingArches: { src: "/images/interiors/living-arches.webp", width: 1600, height: 1197, alt: "Living room with arched windows and grey sofas", credit: { author: "amir hossein", source: "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-large-window-bYqaOabPmTk" } },
  interiorsLivingWood: { src: "/images/interiors/living-wood.webp", width: 1600, height: 1200, alt: "Living room with timber ceiling and tan leather sofa", credit: { author: "Collov Home Design", source: "https://unsplash.com/photos/living-room-with-brown-sofa-and-glass-window-4_jQL4JCS98" } },
  interiorsBedroomDark: { src: "/images/interiors/bedroom-dark.webp", width: 1600, height: 900, alt: "Bedroom with dark timber walls and warm lighting", credit: { author: "POOJAN THANEKAR", source: "https://unsplash.com/photos/modern-bedroom-with-wooden-accents-and-soft-lighting-u-RIsXlI8Q8" } },
  interiorsBedroomLight: { src: "/images/interiors/bedroom-light.webp", width: 1600, height: 900, alt: "Bright bedroom with gallery wall", credit: { author: "Spacejoy", source: "https://unsplash.com/photos/bedroom-with-bed-and-wall-art-XM-miHibz64" } },
  interiorsKitchenWood: { src: "/images/interiors/kitchen-wood.webp", width: 1600, height: 1067, alt: "Kitchen with timber cabinets and black island", credit: { author: "Frames For Your Heart", source: "https://unsplash.com/photos/brown-wooden-kitchen-cabinet-JDBVXignFdA" } },
  interiorsKitchenBright: { src: "/images/interiors/kitchen-bright.webp", width: 1600, height: 2400, alt: "Bright kitchen with timber units opening to a garden", credit: { author: "Jason Briscoe", source: "https://unsplash.com/photos/white-wooden-kitchen-island-and-cupboard-cabinets-near-glass-panel-door-AQl-J19ocWE" } },
  interiorsDining: { src: "/images/interiors/dining.webp", width: 1600, height: 1301, alt: "Dining room with globe pendant lights", credit: { author: "Kam Idris", source: "https://unsplash.com/photos/a-kitchen-with-a-table-and-chairs-3-GXEUE_sCc" } },
  furnitureSofaVelvet: { src: "/images/furniture/sofa-velvet.webp", width: 1200, height: 800, alt: "Green velvet three-seater sofa", credit: { author: "Phillip Goldsberry", source: "https://unsplash.com/photos/green-fabric-sofa-fZuleEfeA1Q" } },
  furnitureSofaLeather: { src: "/images/furniture/sofa-leather.webp", width: 1200, height: 1200, alt: "Tan leather tufted sofa", credit: { author: "personalgraphic.com", source: "https://unsplash.com/photos/a-brown-leather-couch-sitting-on-top-of-a-white-floor-4Co4l84sJWg" } },
  furnitureSofaBoucle: { src: "/images/furniture/sofa-boucle.webp", width: 1200, height: 1500, alt: "Rounded cream bouclé armchair", credit: { author: "Kevin Shek", source: "https://unsplash.com/photos/a-white-couch-sitting-on-top-of-a-white-floor-kcxZ-YUZ8VE" } },
  furnitureArmchairAmber: { src: "/images/furniture/armchair-amber.webp", width: 1200, height: 800, alt: "Amber mid-century armchair", credit: { author: "Lukas Juhas", source: "https://unsplash.com/photos/brown-wooden-framed-beige-padded-chair-WcEowyGAItU" } },
  furnitureArmchairWing: { src: "/images/furniture/armchair-wing.webp", width: 1200, height: 1803, alt: "Mustard wingback armchair", credit: { author: "Laura Chouette", source: "https://unsplash.com/photos/a-yellow-chair-with-a-pillow-on-top-of-it-HUnrPHgMHsA" } },
  furnitureDiningSet: { src: "/images/furniture/dining-set.webp", width: 1200, height: 1600, alt: "Timber dining table with black chairs", credit: { author: "Rumman Amin", source: "https://unsplash.com/photos/blue-ceramic-vase-on-brown-wooden-table-H6iJaMTm2XM" } },
  furnitureDiningRattan: { src: "/images/furniture/dining-rattan.webp", width: 1200, height: 770, alt: "Rattan dining chairs at a timber table", credit: { author: "Liana Mikah", source: "https://unsplash.com/photos/brown-wooden-table-with-chairs-dpv12vxg_aw" } },
  furnitureSideTable: { src: "/images/furniture/side-table.webp", width: 1200, height: 800, alt: "Round side table and leather pouf", credit: { author: "Jason Leung", source: "https://unsplash.com/photos/brown-ottoman-and-small-side-table-against-orange-wall-Wh9YEd_gq38" } },
  furniturePendantCopper: { src: "/images/furniture/pendant-copper.webp", width: 1200, height: 1800, alt: "Copper dome pendant lamps", credit: { author: "Jean-Philippe Delberghe", source: "https://unsplash.com/photos/turned-on-pendant-lamps-Ry9WBo3qmoc" } },
  furniturePendantTimber: { src: "/images/furniture/pendant-timber.webp", width: 1200, height: 1800, alt: "Slatted timber pendant lamps", credit: { author: "Anne Nygård", source: "https://unsplash.com/photos/three-gold-pendant-lamps-6GgkEIqnPfQ" } },
  furnitureSideboard: { src: "/images/furniture/sideboard.webp", width: 1200, height: 1800, alt: "Mid-century timber sideboard", credit: { author: "Urban Vintage", source: "https://unsplash.com/photos/a-living-room-with-white-walls-and-a-white-rug-txCCeMy4lOM" } },
  furnitureDresser: { src: "/images/furniture/dresser.webp", width: 1200, height: 800, alt: "Timber chest of drawers against a peach wall", credit: { author: "Earl Wilcox", source: "https://unsplash.com/photos/brown-wooden-drawer-with-painting-3xpQCOOe6hM" } },
  furnitureBed: { src: "/images/furniture/bed.webp", width: 1200, height: 1800, alt: "Bed with timber headboard and terracotta linen", credit: { author: "Erik Mclean", source: "https://unsplash.com/photos/white-bed-linen-on-bed-Ij9nIghkI6k" } },
} satisfies Record<string, SiteImage>

export type ImageKey = keyof typeof images
